apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "charts.fullname" . }}-control
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "charts.fullname" . }}-control
subjects:
  - kind: ServiceAccount
    name: {{ include "charts.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}